# Generated by Django 6.0.2 on 2026-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadreport_issue_fraudcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadreport',
            name='fraud_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadreport',
            name='total_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadreport',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
    ]
